### ISSUE TITLE
Response problem java.util.ArrayList cannot be cast to class org.springframework.http.ResponseEntity

### ISSUE THREAD

**Issue by GregSino** [ekim197711/binance-api-springboot#1]
Hi Mike,

And to begin with, thank you so much for your tutorial. It helped me a lot to have a better knowledge with rest application.

Actually, I have a problem with the exctractCandles method.

I get the response in the console exactly like you, but if I execute a request from postman, I have this error message:

`"class java.util.ArrayList cannot be cast to class org.springframework.http.ResponseEntity (java.util.ArrayList is in module java.base of loader 'bootstrap'; org.springframework.http.ResponseEntity is in unnamed module of loader 'app'`

Here is the method inside the controler:

`
@GetMapping("/{symbolBeforeConvertion}/{intervalBeforeConvertion}/{limitBeforeConvertion}")

    public ResponseEntity<CandleItem> findCandleCollectBySymbol(
            @PathVariable String symbolBeforeConvertion,
            @PathVariable String intervalBeforeConvertion,
            @PathVariable String limitBeforeConvertion) {

        Symbol symbol = Symbol.valueOf(symbolBeforeConvertion);
        Interval interval = Interval.valueOf(intervalBeforeConvertion);
        Limit limit = Limit.valueOf(limitBeforeConvertion);

        List<CandleItem> candleItems = candleCollectService.extractCandles(symbol, interval, limit);

        Assertions.assertTrue(candleItems.size() > 0);
        candleItems.forEach(e -> {
            System.out.println(e.simpleToString());
        });

        return (ResponseEntity<CandleItem>) candleItems;

    }`

Here is the service:

`public List<CandleItem> extractCandles(Symbol symbol, Interval interval, Limit limit) {

        log.info("Extract candles: symbol {} interval {} limit {}", symbol, interval, limit);
        RestTemplate rt = new RestTemplate();

        URI url = UriComponentsBuilder.fromHttpUrl(candleCollectConfiguration.getCandleUrlPrefix()
                + candleCollectConfiguration.getCandleUrl())

                .queryParam(candleCollectConfiguration.getCandleUrlQuerySymbol(),
                        symbol.getCode())

                .queryParam(candleCollectConfiguration.getCandleUrlQueryInterval(),
                        interval.getCode())

                .queryParam(candleCollectConfiguration.getCandleUrlQueryLimit(), limit.getCode())
                .build().toUri();

        log.debug("Url: {}", url);
        ResponseEntity<List<List<Object>>> exchange = rt.exchange(new RequestEntity<>(HttpMethod.GET, url),
                new ParameterizedTypeReference<>() {  });

        List<List<Object>> response = exchange.getBody();

        if (response == null) {
            log.warn("No response from service!");
            return new ArrayList<>();
        }`

And finally my request:

`http://localhost:8080/app/api/candlecollect/BTCUSDT/FIFTEEN_MIN/CINQCENT`

Hope you can help me! and for thanks again for your work.

EDIT: Sorry for the bug with the code. Impossible to put everything inside the quotes...

**Comment by GregSino** [comment]
Finally I found the solution: 

Just need to simplify the answer:

```
List<CandleItem> candleItems = candleCollectService.extractCandles(symbol, interval, limit);

        Assertions.assertTrue(candleItems.size() > 0);
        candleItems.forEach(e -> {
            System.out.println(e.simpleToString());
        });

        return candleItems;
```

**Comment by ekim197711** [comment]
I am happy to hear.

Next time try my discord server for a faster response + others to help.

https://discord.gg/vaV9G4wnpE

Mvh.
Mike Møller Nielsen
+45 61600005
www.codeinvestigator.com
Code Investigator - part of URSolutions
Cvr: 27503608

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
